[project]
authors = ["Dmitry Salin <dmitry.salin@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "The low-level `io_uring` userspace interface"
name = "io_uring"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "==25.1.1"
